export const LOAD_USER_START = "LOAD_USER_START";
export const LOAD_USER_SUCESS = "LOAD_USER_SUCESS";
export const LOAD_USER_ERROR = "LOAD_USER_ERROR";

export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";

export const DELETED_USER_START = "DELETED_USER_START";
export const DELETED_USER_SUCCESS = "DELETED_USER_SUCCESS";
export const DELETED_USER_ERROR = "DELETED_USER_ERROR";

export const UPDATE_USER_START = "UPDATE_USER_START";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
